<?php

return [
    'align_multiline_comment' => [
        'comment_type' => 'phpdocs_like',
    ],
    'array_indentation' => true,
    'array_syntax'      => [
        'syntax' => 'short',
    ],
    'backtick_to_shell_exec' => true,
    'binary_operator_spaces' => [
        'default'   => 'align_single_space_minimal',
        'operators' => [
            '|' => 'no_space',
        ],
    ],
    'blank_line_after_namespace'   => true,
    'blank_line_after_opening_tag' => true,
    'blank_line_before_statement'  => [
        'statements' => [
            'break',
            'case',
            'continue',
            'declare',
            'default',
            'die',
            'do',
            'exit',
            'for',
            'foreach',
            'goto',
            'if',
            'include',
            'include_once',
            'require',
            'require_once',
            'return',
            'switch',
            'throw',
            'try',
            'while',
            'yield',
        ],
    ],
    'braces' => [
        'allow_single_line_closure'                   => true,
        'position_after_anonymous_constructs'         => 'same',
        'position_after_control_structures'           => 'same',
        'position_after_functions_and_oop_constructs' => 'same',
    ],
    'cast_spaces' => [
        'space' => 'none',
    ],
    'class_attributes_separation' => [
        'elements' => [
            // 'const',
            // 'property',
            'method',
        ],
    ],
    'class_definition' => [
        'multi_line_extends_each_single_line' => false,
        'single_item_single_line'             => true,
        'single_line'                         => false,
    ],
    'class_keyword_remove'       => false,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'compact_nullable_typehint'  => true,
    'concat_space'               => [
        'spacing' => 'none',
    ],
    'constant_case' => [
        'case' => 'lower',
    ],
    'declare_equal_normalize' => [
        'space' => 'none',
    ],
    'doctrine_annotation_array_assignment' => true,
    'doctrine_annotation_braces'           => true,
    'doctrine_annotation_indentation'      => true,
    'doctrine_annotation_spaces'           => true,
    'elseif'                               => true,
    'encoding'                             => true,
    'escape_implicit_backslashes'          => [
        'double_quoted'  => true,
        'heredoc_syntax' => true,
        'single_quoted'  => false,
    ],
    'explicit_indirect_variable'   => true,
    'explicit_string_variable'     => true,
    'final_static_access'          => true,
    'full_opening_tag'             => true,
    'fully_qualified_strict_types' => true,
    'function_declaration'         => [
        'closure_function_spacing' => 'none',
    ],
    'function_typehint_space'          => true,
    'general_phpdoc_annotation_remove' => [
        'annotations' => [
            'author',
        ],
    ],
    'global_namespace_import' => [
        'import_classes'   => true,
        'import_constants' => false,
        'import_functions' => false,
    ],
    'header_comment'      => false,
    'heredoc_indentation' => true,
    'heredoc_to_nowdoc'   => true,
    'include'             => true,
    'increment_style'     => [
        'style' => 'post',
    ],
    'indentation_type'            => true,
    'line_ending'                 => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax'                 => [
        'syntax' => 'short',
    ],
    'lowercase_cast'             => true,
    'lowercase_keywords'         => true,
    'lowercase_static_reference' => true,
    'magic_constant_casing'      => true,
    'magic_method_casing'        => true,
    'method_argument_space'      => [
        'after_heredoc'                    => true,
        'keep_multiple_spaces_after_comma' => false,
        'on_multiline'                     => 'ensure_fully_multiline',
    ],
    'method_chaining_indentation'            => true,
    'multiline_comment_opening_closing'      => true,
    'multiline_whitespace_before_semicolons' => [
        'strategy' => 'no_multi_line',
    ],
    'native_function_casing'                  => true,
    'native_function_type_declaration_casing' => true,
    'new_with_braces'                         => true,
    'no_alternative_syntax'                   => true,
    'no_binary_string'                        => true,
    'no_blank_lines_after_class_opening'      => false,
    'no_blank_lines_after_phpdoc'             => true,
    'no_blank_lines_before_namespace'         => false,
    'no_break_comment'                        => true,
    'no_closing_tag'                          => true,
    'no_empty_comment'                        => true,
    'no_empty_phpdoc'                         => true,
    'no_empty_statement'                      => true,
    'no_extra_blank_lines'                    => true,
    'no_leading_import_slash'                 => true,
    'no_leading_namespace_whitespace'         => true,
    'no_mixed_echo_print'                     => [
        'use' => 'echo',
    ],
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_null_property_initialization'             => false,
    'no_short_bool_cast'                          => true,
    'no_short_echo_tag'                           => true,
    'no_singleline_whitespace_before_semicolons'  => true,
    'no_spaces_after_function_name'               => true,
    'no_spaces_around_offset'                     => [
        'positions' => [
            'inside',
            'outside',
        ],
    ],
    'no_spaces_inside_parenthesis'          => true,
    'no_superfluous_elseif'                 => true,
    'no_superfluous_phpdoc_tags'            => false,
    'no_trailing_comma_in_list_call'        => true,
    'no_trailing_comma_in_singleline_array' => true,
    'no_trailing_whitespace'                => true,
    'no_trailing_whitespace_in_comment'     => true,
    'no_unneeded_control_parentheses'       => [
        'statements' => [
            'break',
            'clone',
            'continue',
            'echo_print',
            'return',
            'switch_case',
            'yield',
        ],
    ],
    'no_unneeded_curly_braces'            => true,
    'no_unneeded_final_method'            => false,
    'no_unset_cast'                       => true,
    'no_unused_imports'                   => true,
    'no_useless_else'                     => true,
    'no_useless_return'                   => true,
    'no_whitespace_before_comma_in_array' => [
        'after_heredoc' => true,
    ],
    'no_whitespace_in_blank_line'                      => true,
    'normalize_index_brace'                            => true,
    'not_operator_with_space'                          => false,
    'not_operator_with_successor_space'                => false,
    'nullable_type_declaration_for_default_null_value' => [
        'use_nullable_type_declaration' => true,
    ],
    'object_operator_without_whitespace' => true,
    'ordered_class_elements'             => [
        'order' => [
            'use_trait',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'construct',
            'destruct',
            'magic',
            'phpunit',
            'method_public',
            'method_protected',
            'method_private',
        ],
        'sortAlgorithm' => 'none',
    ],
    'ordered_imports' => [
        'sort_algorithm' => 'alpha',
        'imports_order'  => [
            'const',
            'class',
            'function',
        ],
    ],

    'php_unit_fqcn_annotation'            => null,
    'php_unit_internal_class'             => null,
    'php_unit_method_casing'              => null,
    'php_unit_ordered_covers'             => null,
    'php_unit_size_class'                 => null,
    'php_unit_test_class_requires_covers' => null,

    'phpdoc_add_missing_param_annotation' => [
        'only_untyped' => false,
    ],
    'phpdoc_align'                  => true,
    'phpdoc_annotation_without_dot' => true,
    'phpdoc_indent'                 => true,
    'phpdoc_inline_tag'             => true,
    'phpdoc_line_span'              => [
        'const'    => 'single',
        'property' => 'single',
        'method'   => 'multi',
    ],
    'phpdoc_no_access'             => false,
    'phpdoc_no_alias_tag'          => false,
    'phpdoc_no_empty_return'       => false,
    'phpdoc_no_package'            => true,
    'phpdoc_no_useless_inheritdoc' => false,
    'phpdoc_order'                 => true,
    'phpdoc_return_self_reference' => true,
    'phpdoc_scalar'                => [
        'types' => [
            'boolean',
            'callback',
            'double',
            'integer',
            'real',
            'str',
        ],
    ],
    'phpdoc_separation'                             => true,
    'phpdoc_single_line_var_spacing'                => true,
    'phpdoc_summary'                                => true,
    'phpdoc_to_comment'                             => true,
    'phpdoc_trim'                                   => true,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_types'                                  => true,
    'phpdoc_types_order'                            => [
        'null_adjustment' => 'always_last',
        'sort_algorithm'  => 'none',
    ],
    'phpdoc_var_annotation_correct_order' => true,
    'phpdoc_var_without_name'             => true,

    'protected_to_private'    => true,
    'return_assignment'       => true,
    'return_type_declaration' => [
        'space_before' => 'none',
    ],
    'self_static_accessor'               => true,
    'semicolon_after_instruction'        => true,
    'short_scalar_cast'                  => true,
    'simple_to_complex_string_variable'  => true,
    'simplified_null_return'             => true,
    'single_blank_line_at_eof'           => true,
    'single_blank_line_before_namespace' => true,
    'single_class_element_per_statement' => [
        'elements' => [
            'const',
            'property',
        ],
    ],
    'single_import_per_statement' => true,
    'single_line_after_imports'   => true,
    'single_line_comment_style'   => [
        'comment_types' => [
            'asterisk',
            'hash',
        ],
    ],
    'single_line_throw' => true,
    'single_quote'      => [
        'strings_containing_single_quote_chars' => true,
    ],
    'single_trait_insert_per_statement' => true,
    'space_after_semicolon'             => [
        'remove_in_empty_for_expressions' => true,
    ],
    'standardize_increment'             => true,
    'standardize_not_equals'            => true,
    'switch_case_semicolon_to_colon'    => true,
    'switch_case_space'                 => true,
    'ternary_operator_spaces'           => true,
    'ternary_to_null_coalescing'        => true,
    'trailing_comma_in_multiline_array' => [
        'after_heredoc' => true,
    ],
    'trim_array_spaces'     => true,
    'unary_operator_spaces' => true,
    'visibility_required'   => [
        'elements' => [
            'property',
            'method',
            'const',
        ],
    ],
    'whitespace_after_comma_in_array' => true,
    'yoda_style'                      => [
        'always_move_variable' => false,
        'equal'                => false,
        'identical'            => false,
        'less_and_greater'     => null,
    ],
];
